service: go-lambda-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}
  memorySize: 256
  timeout: 15
  environment:
    API_KEY: ${env:API_KEY}
    PORT: ${env:PORT, '8080'}
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:*:*:*'

# No plugins needed since we build the binary ourselves

functions:
  api:
    handler: bootstrap
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY
    environment:
      API_KEY: ${env:API_KEY}

# Exclude everything except the binary
package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bootstrap
